import requests
import re
from bs4 import BeautifulSoup
import concurrent.futures
import time

scoutURL = "https://universalstorebuy.myshopify.com/policies/privacy-policy"

scouting_URLS = [
    # "https://oveora.com/policies/privacy-policy",
    "https://pacificpk.store/policies/privacy-policy",
    "https://packify-reel.myshopify.com/policies/privacy-policy",
    "https://paradiseelixirs.store/policies/privacy-policy",
    # "https://pardonruined.com/policies/privacy-policy",
    "https://patitasviralesargentina.myshopify.com/policies/privacy-policy",
    "https://pawperimeter.com/policies/privacy-policy",
    "https://pawprint-lab.myshopify.com/policies/privacy-policy",
    "https://pawtraitstudio.online/policies/privacy-policy",
    "https://pdfzone.myshopify.com/policies/privacy-policy",
    'https://03fkf8-8b.myshopify.com/policies/privacy-policy',
'https://0f1b90-2.myshopify.com/policies/privacy-policy',
'https://0whygp-g0.myshopify.com/policies/privacy-policy',
'https://0yi5cx-p7.myshopify.com/policies/privacy-policy',
'https://1evyn9-p0.myshopify.com/policies/privacy-policy',
'https://1f7iuj-yv.myshopify.com/policies/privacy-policy',
'https://1fgrbj-hv.myshopify.com/policies/privacy-policy',
'https://27v6ju-85.myshopify.com/policies/privacy-policy',
'https://3gu1wc-xg.myshopify.com/policies/privacy-policy',
'https://3pmfear.com/policies/privacy-policy',
'https://42nd-store-2.myshopify.com/policies/privacy-policy',
'https://5ksxuu-1p.myshopify.com/policies/privacy-policy',
'https://9a7167-2.myshopify.com/policies/privacy-policy',
'https://9agupz-bx.myshopify.com/policies/privacy-policy',
'https://acasadoaco.com/policies/privacy-policy',
'https://acelice.com/policies/privacy-policy',
'https://acopioshopgt.myshopify.com/policies/privacy-policy',
'https://addictstreet.com/policies/privacy-policy',
'https://adiosacidez.store/policies/privacy-policy',
'https://adminpc-tienda.com/policies/privacy-policy',
'https://aerocart-15.myshopify.com/policies/privacy-policy',
'https://afmall-af.myshopify.com/policies/privacy-policy',
'https://afriexpress22.myshopify.com/policies/privacy-policy',
'https://afrishopp.store/policies/privacy-policy',
'https://afristoretz.myshopify.com/policies/privacy-policy',
'https://ahimsaproducts.com/policies/privacy-policy',
'https://airox.store/policies/privacy-policy',
'https://akazastreetwear.myshopify.com/policies/privacy-policy',
'https://akho.store/policies/privacy-policy',
'https://aleniya.com/policies/privacy-policy',
'https://alexnails-pressonnails.com/policies/privacy-policy',
'https://alina-brasov.ro/policies/privacy-policy',
'https://all-in-one-store-637203.myshopify.com/policies/privacy-policy',
'https://alvayna.com/policies/privacy-policy',
'https://amazonpay4.myshopify.com/policies/privacy-policy',
'https://ambanistore.com/policies/privacy-policy',
'https://amzkart-shop.myshopify.com/policies/privacy-policy',
'https://amzokdefabrica.shop/policies/privacy-policy',
'https://andradeheath.shop/policies/privacy-policy',
'https://andreaterecomienda.co/policies/privacy-policy',
'https://anjalique-2.myshopify.com/policies/privacy-policy',
'https://ankhaway.myshopify.com/policies/privacy-policy',
'https://aoiva.com/policies/privacy-policy',
'https://apex-kart-2.myshopify.com/policies/privacy-policy',
'https://apexheat.co/policies/privacy-policy',
'https://apexwintergear.com/policies/privacy-policy',
'https://api.ppspy.com/policies/privacy-policy',
'https://app.ppspy.com/policies/privacy-policy',
'https://approx-creation-t5.myshopify.com/policies/privacy-policy',
'https://apps.shopify.com/policies/privacy-policy',
'https://aquabeat12.myshopify.com/policies/privacy-policy',
'https://arcamediahub.myshopify.com/policies/privacy-policy',
'https://arcanecomforts.store/policies/privacy-policy',
'https://ardenashop.com/policies/privacy-policy',
'https://ascendpedia.com/policies/privacy-policy',
'https://asleepysoldier.me/policies/privacy-policy',
'https://asosoffers.myshopify.com/policies/privacy-policy',
'https://astoriamilano-italy.myshopify.com/policies/privacy-policy',
'https://astraebrand.com/policies/privacy-policy',
'https://astralacademy.shop/policies/privacy-policy',
'https://astryshop.com/policies/privacy-policy',
'https://atbw2b-c0.myshopify.com/policies/privacy-policy',
'https://atelierepure-paris.fr/policies/privacy-policy',
'https://atupuertashopchile.myshopify.com/policies/privacy-policy',
'https://audiocity.art/policies/privacy-policy',
'https://auraaestetix.com/policies/privacy-policy',
'https://auraattiremumbai.myshopify.com/policies/privacy-policy',
'https://auraesthe.com.tr/policies/privacy-policy',
'https://aurainternacional.myshopify.com/policies/privacy-policy',
'https://auralis-4383.myshopify.com/policies/privacy-policy',
'https://auravybe.shop/policies/privacy-policy',
'https://aurelianoir.de/policies/privacy-policy',
'https://aushadh-life.myshopify.com/policies/privacy-policy',
'https://ausvira.com/policies/privacy-policy',
'https://autocarmorra.com/policies/privacy-policy',
'https://autolinkstore.com/policies/privacy-policy',
'https://autominix.myshopify.com/policies/privacy-policy',
'https://automobilli.com/policies/privacy-policy',
'https://autopremier.shop/policies/privacy-policy',
'https://awesomepdfs.myshopify.com/policies/privacy-policy',
'https://axiom-gear-2.myshopify.com/policies/privacy-policy',
'https://b10nhz-t4.myshopify.com/policies/privacy-policy',
'https://b7tn30-8h.myshopify.com/policies/privacy-policy',
'https://bagkulture.myshopify.com/policies/privacy-policy',
'https://bandariya.com/policies/privacy-policy',
'https://baytikk.com/policies/privacy-policy',
'https://bbcorneronlinestore.myshopify.com/policies/privacy-policy',
'https://beastlift.com/policies/privacy-policy',
'https://beastoo-prime-store.myshopify.com/policies/privacy-policy',
'https://beauty-bureau-2.myshopify.com/policies/privacy-policy',
'https://bebeamore.com/policies/privacy-policy',
'https://beherworld.in/policies/privacy-policy',
'https://berzerk.online/policies/privacy-policy',
'https://bettersouk.com/policies/privacy-policy',
'https://beyondalpha.site/policies/privacy-policy',
'https://bgbkqy-bd.myshopify.com/policies/privacy-policy',
'https://bharatkart-4335.myshopify.com/policies/privacy-policy',
'https://bigdeal-9667.myshopify.com/policies/privacy-policy',
'https://bimo-9570.myshopify.com/policies/privacy-policy',
'https://biolevel.store/policies/privacy-policy',
'https://biopulse-labs.myshopify.com/policies/privacy-policy',
'https://bjornmark.com/policies/privacy-policy',
'https://black-x-boot.myshopify.com/policies/privacy-policy',
'https://blackdadlk.myshopify.com/policies/privacy-policy',
'https://blazely-3.myshopify.com/policies/privacy-policy',
'https://blessdept.com/policies/privacy-policy',
'https://blh-4.myshopify.com/policies/privacy-policy',
'https://blocktorch-2.myshopify.com/policies/privacy-policy',
'https://bloomee.se/policies/privacy-policy',
'https://bloomhydrate.myshopify.com/policies/privacy-policy',
'https://bls-digital-hub.myshopify.com/policies/privacy-policy',
'https://bobody.ma/policies/privacy-policy',
'https://boleterafxmini.myshopify.com/policies/privacy-policy',
'https://bonzeraussies.com/policies/privacy-policy',
'https://books4you-7397.myshopify.com/policies/privacy-policy',
'https://boostas-merch.myshopify.com/policies/privacy-policy',
'https://bouncera.shop/policies/privacy-policy',
'https://boutiquesanspoils.myshopify.com/policies/privacy-policy',
'https://bralissa.myshopify.com/policies/privacy-policy',
'https://bravadostudio-return.com/policies/privacy-policy',
'https://breezoau.com/policies/privacy-policy',
'https://brimexx.store/policies/privacy-policy',
'https://btcnewgame.store/policies/privacy-policy',
'https://buckhornholler.com/policies/privacy-policy',
'https://buildsbricklabstore.com/policies/privacy-policy',
'https://builtfrompain.co.uk/policies/privacy-policy',
'https://bulit-to-bloom-co.myshopify.com/policies/privacy-policy',
'https://burnfitlab.myshopify.com/policies/privacy-policy',
'https://buylo.store/policies/privacy-policy',
'https://bvfhv.shop/policies/privacy-policy',
'https://bydement.shop/policies/privacy-policy',
'https://bydomira.com/policies/privacy-policy',
'https://byraf-4.myshopify.com/policies/privacy-policy',
'https://bzbf1x-rh.myshopify.com/policies/privacy-policy',
'https://c4rnbq-5x.myshopify.com/policies/privacy-policy',
'https://c6ution.com/policies/privacy-policy',
'https://calmescape.store/policies/privacy-policy',
'https://calmthatpaw.myshopify.com/policies/privacy-policy',
'https://cammapilates.com/policies/privacy-policy',
'https://cantinhodonoel.com/policies/privacy-policy',
'https://care-hut-2.myshopify.com/policies/privacy-policy',
'https://cargo-10008.myshopify.com/policies/privacy-policy',
'https://casadascoisaboas-brasil.myshopify.com/policies/privacy-policy',
'https://celena-studio.com/policies/privacy-policy',
'https://celteria.com/policies/privacy-policy',
'https://celviora.shop/policies/privacy-policy',
'https://cgbessentials.myshopify.com/policies/privacy-policy',
'https://charzdeos.myshopify.com/policies/privacy-policy',
'https://cheiforganic.online/policies/privacy-policy',
'https://cheka.shop/policies/privacy-policy',
'https://chile-9345.myshopify.com/policies/privacy-policy',
'https://choronex.com/policies/privacy-policy',
'https://chrome.google.com/policies/privacy-policy',
'https://clicknshop34.myshopify.com/policies/privacy-policy',
'https://clickship.in/policies/privacy-policy',
'https://comfyangel.ca/policies/privacy-policy',
'https://completely-healthy.myshopify.com/policies/privacy-policy',
'https://conakry-mall.myshopify.com/policies/privacy-policy',
'https://condadoltda.com/policies/privacy-policy',
'https://confiserie-vergissmeinnicht.de/policies/privacy-policy',
'https://cookindustry.com/policies/privacy-policy',
'https://coolonewinter.store/policies/privacy-policy',
'https://corapduragi.com/policies/privacy-policy',
'https://cords-9375.myshopify.com/policies/privacy-policy',
'https://corehalo.com.au/policies/privacy-policy',
'https://corvatti.com/policies/privacy-policy',
'https://cosmeticallybp.myshopify.com/policies/privacy-policy',
'https://cozyhoody.nl/policies/privacy-policy',
'https://cozyvias.store/policies/privacy-policy',
'https://cozzykart.myshopify.com/policies/privacy-policy',
'https://craftmart.store/policies/privacy-policy',
'https://crazyworldshop.com/policies/privacy-policy',
'https://cristiano-feliz.myshopify.com/policies/privacy-policy',
'https://crossover-store.co.za/policies/privacy-policy',
'https://crystaz-2.myshopify.com/policies/privacy-policy',
'https://cuencum.com/policies/privacy-policy',
'https://cumulos.store/policies/privacy-policy',
'https://cunz01-f6.myshopify.com/policies/privacy-policy',
'https://curate-life-2.myshopify.com/policies/privacy-policy',
'https://curemala.myshopify.com/policies/privacy-policy',
'https://curlwave.store/policies/privacy-policy',
'https://cylvoir.shop/policies/privacy-policy',
'https://daciawear.com/policies/privacy-policy',
'https://dailymagic-deals.myshopify.com/policies/privacy-policy',
'https://dalenu.com/policies/privacy-policy',
'https://damday.de/policies/privacy-policy',
'https://daraz.store/policies/privacy-policy',
'https://ddcs4a-0n.myshopify.com/policies/privacy-policy',
'https://ddi8xd-g0.myshopify.com/policies/privacy-policy',
'https://ddxdcb-iy.myshopify.com/policies/privacy-policy',
'https://deanlora-london.co.uk/policies/privacy-policy',
'https://decoration-world-2.myshopify.com/policies/privacy-policy',
'https://dekcrate.com/policies/privacy-policy',
'https://delaaguilar.shop/policies/privacy-policy',
'https://deltadeals1.myshopify.com/policies/privacy-policy',
'https://dentavell.com/policies/privacy-policy',
'https://dermaeg.myshopify.com/policies/privacy-policy',
'https://deschuhshop.com/policies/privacy-policy',
'https://desifindsindia.myshopify.com/policies/privacy-policy',
'https://deskaura.tech/policies/privacy-policy',
'https://diauna.com/policies/privacy-policy',
'https://dicasprime.com/policies/privacy-policy',
'https://djr1yf-w1.myshopify.com/policies/privacy-policy',
'https://dloutlet.co.za/policies/privacy-policy',
'https://dncweb.myshopify.com/policies/privacy-policy',
'https://doazor.com/policies/privacy-policy',
'https://docemorada-com-br.myshopify.com/policies/privacy-policy',
'https://donitasquefacturan.online/policies/privacy-policy',
'https://dorvento.store/policies/privacy-policy',
'https://douglasparfunn.com/policies/privacy-policy',
'https://dp-concerts.com/policies/privacy-policy',
'https://dragontrim.shop/policies/privacy-policy',
'https://drkopper.com/policies/privacy-policy',
'https://dropfinity.co/policies/privacy-policy',
'https://drsumal.myshopify.com/policies/privacy-policy',
'https://dwt-germany.de/policies/privacy-policy',
'https://dysfinite.com/policies/privacy-policy',
'https://easy-style.fr/policies/privacy-policy',
'https://ecllipselondon.com/policies/privacy-policy',
'https://ecn100bio.myshopify.com/policies/privacy-policy',
'https://ejercicioypotencia.com/policies/privacy-policy',
'https://el-patron-shop-2.myshopify.com/policies/privacy-policy',
'https://electromart-6534.myshopify.com/policies/privacy-policy',
'https://electroweb-9208.myshopify.com/policies/privacy-policy',
'https://elenapraha.com/policies/privacy-policy',
'https://elevateplus.store/policies/privacy-policy',
'https://elitenexo.myshopify.com/policies/privacy-policy',
'https://elmassouna.store/policies/privacy-policy',
'https://eloriax.com/policies/privacy-policy',
'https://emma-lancaster.uk/policies/privacy-policy',
'https://emocionfemenina.shop/policies/privacy-policy',
'https://emporiums.live/policies/privacy-policy',
'https://emptystudios.eu/policies/privacy-policy',
'https://enayaj.com/policies/privacy-policy',
'https://encantosstore.com/policies/privacy-policy',
'https://englishpathoficial.online/policies/privacy-policy',
'https://engraced.ie/policies/privacy-policy',
'https://enovashape.com/policies/privacy-policy',
'https://esences.com/policies/privacy-policy',
'https://esporatto.online/policies/privacy-policy',
'https://essara.net/policies/privacy-policy',
'https://essence-d-ivoire.myshopify.com/policies/privacy-policy',
'https://eurobakerycafe.com/policies/privacy-policy',
'https://evertallo.myshopify.com/policies/privacy-policy',
'https://evionn.com/policies/privacy-policy',
'https://exoticsca.com/policies/privacy-policy',
'https://expressdeal1.myshopify.com/policies/privacy-policy',
'https://fashionablyyoursboutique.store/policies/privacy-policy',
'https://feelien.com/policies/privacy-policy',
'https://feloriaskin.com/policies/privacy-policy',
'https://fetchboy.co.uk/policies/privacy-policy',
'https://fibrapro.store/policies/privacy-policy',
'https://fioralux.de/policies/privacy-policy',
'https://fitoraofficial.myshopify.com/policies/privacy-policy',
'https://fivvanuvii.com/policies/privacy-policy',
'https://flamesa.co.uk/policies/privacy-policy',
'https://fleecezy.nl/policies/privacy-policy',
'https://flexfusion-fusion.myshopify.com/policies/privacy-policy',
'https://flintdiffusers.com/policies/privacy-policy',
'https://floffina.com/policies/privacy-policy',
'https://floreux.store/policies/privacy-policy',
'https://flufixx.myshopify.com/policies/privacy-policy',
'https://flymade.co/policies/privacy-policy',
'https://foldimateofficial.shop/policies/privacy-policy',
'https://forevertributes.shop/policies/privacy-policy',
'https://fotbollfun.com/policies/privacy-policy',
'https://fourdubs.ca/policies/privacy-policy',
'https://freedropshippinguniversity.online/policies/privacy-policy',
'https://freezefoot.store/policies/privacy-policy',
'https://funneetees-2.myshopify.com/policies/privacy-policy',
'https://fusionproducts.store/policies/privacy-policy',
'https://fyndprime.com/policies/privacy-policy',
'https://gabeismotivated.com/policies/privacy-policy',
'https://gadgettwaalle.myshopify.com/policies/privacy-policy',
'https://gadgettwaallee.myshopify.com/policies/privacy-policy',
'https://galixo.store/policies/privacy-policy',
'https://getascendfit.com/policies/privacy-policy',
'https://getglitchie.com/policies/privacy-policy',
'https://getglowrituals.com/policies/privacy-policy',
'https://gethealight.com/policies/privacy-policy',
'https://getlumivive.com/policies/privacy-policy',
'https://getstartedtiktok.pxf.io/policies/privacy-policy',
'https://getwell.store/policies/privacy-policy',
'https://gharsebhejo.com/policies/privacy-policy',
'https://giamere.myshopify.com/policies/privacy-policy',
'https://gilanwohler.com/policies/privacy-policy',
'https://gizlibolmetr.myshopify.com/policies/privacy-policy',
'https://glamauraparis.com/policies/privacy-policy',
'https://globaldropsarg.myshopify.com/policies/privacy-policy',
'https://globalonewatch.store/policies/privacy-policy',
'https://glowashop.com/policies/privacy-policy',
'https://glowmart.website/policies/privacy-policy',
'https://glowmax-auto.myshopify.com/policies/privacy-policy',
'https://glowpawessentials.myshopify.com/policies/privacy-policy',
'https://gnagara-business.myshopify.com/policies/privacy-policy',
'https://gobalyx.myshopify.com/policies/privacy-policy',
'https://gomarketeasy.com/policies/privacy-policy',
'https://goraeit.myshopify.com/policies/privacy-policy',
'https://gotoblendd.myshopify.com/policies/privacy-policy',
'https://gr.zrevnika.com/policies/privacy-policy',
'https://grapplingsmashy.com.au/policies/privacy-policy',
'https://grevo.io/policies/privacy-policy',
'https://greyfordlondon.com/policies/privacy-policy',
'https://grouchy.store/policies/privacy-policy',
'https://grovelaneshop.com/policies/privacy-policy',
'https://grumpynators.myshopify.com/policies/privacy-policy',
'https://gummybrasil.site/policies/privacy-policy',
'https://h1pn1n-ky.myshopify.com/policies/privacy-policy',
'https://hakim-reitim.myshopify.com/policies/privacy-policy',
'https://happy-board.shop/policies/privacy-policy',
'https://happy-dove-studios.myshopify.com/policies/privacy-policy',
'https://happycratecreations.com/policies/privacy-policy',
'https://happyflops.ph/policies/privacy-policy',
'https://happytalkies.myshopify.com/policies/privacy-policy',
'https://hardvoro.com/policies/privacy-policy',
'https://harper-montreal.ca/policies/privacy-policy',
'https://havaianasbrasil.site/policies/privacy-policy',
'https://healthyliving3.myshopify.com/policies/privacy-policy',
'https://heatcove.com/policies/privacy-policy',
'https://heavensblush.com/policies/privacy-policy',
'https://helafure.com/policies/privacy-policy',
'https://helperi.myshopify.com/policies/privacy-policy',
'https://hersleva.com/policies/privacy-policy',
'https://hgmtad-u0.myshopify.com/policies/privacy-policy',
'https://hhomewares.myshopify.com/policies/privacy-policy',
'https://hi-rez.org/policies/privacy-policy',
'https://highgeartoys-2.myshopify.com/policies/privacy-policy',
'https://hntrendy.shop/policies/privacy-policy',
'https://hollywool.store/policies/privacy-policy',
'https://homeyhubplus.com/policies/privacy-policy',
'https://horizonstore.net/policies/privacy-policy',
'https://hostore.online/policies/privacy-policy',
'https://housybox.com/policies/privacy-policy',
'https://houzie.shop/policies/privacy-policy',
'https://hr15rb-e4.myshopify.com/policies/privacy-policy',
'https://htbrf0-ka.myshopify.com/policies/privacy-policy',
'https://hurainhub.store/policies/privacy-policy',
'https://hydraulicstores.co.za/policies/privacy-policy',
'https://hydroholdus.myshopify.com/policies/privacy-policy',
'https://hydroshld.com/policies/privacy-policy',
'https://i92n1d-2t.myshopify.com/policies/privacy-policy',
'https://ia9ncj-cq.myshopify.com/policies/privacy-policy',
'https://ibadatwears.store/policies/privacy-policy',
'https://iberoteca.com/policies/privacy-policy',
'https://igkshop.store/policies/privacy-policy',
'https://importadoraagricola.com/policies/privacy-policy',
'https://instant-kiff.fr/policies/privacy-policy',
'https://ivchef-ah.myshopify.com/policies/privacy-policy',
'https://j-b-l-mexico.myshopify.com/policies/privacy-policy',
'https://jacsresales.com/policies/privacy-policy',
'https://jadevaults.com/policies/privacy-policy',
'https://jaebae.store/policies/privacy-policy',
'https://jainamstore.com/policies/privacy-policy',
'https://jay-shree-ram-store-7918.myshopify.com/policies/privacy-policy',
'https://jemvesportswear.com/policies/privacy-policy',
'https://jinseii.com/policies/privacy-policy',
'https://jowana.fr/policies/privacy-policy',
'https://joylo.in/policies/privacy-policy',
'https://joypallete.com/policies/privacy-policy',
'https://jpacademy.info/policies/privacy-policy',
'https://jrnpdh-v0.myshopify.com/policies/privacy-policy',
'https://jsrprintwear.myshopify.com/policies/privacy-policy',
'https://kabekokusu.com/policies/privacy-policy',
'https://karibiyonnroyalty.com/policies/privacy-policy',
'https://kelsashop.com/policies/privacy-policy',
'https://keralux.shop/policies/privacy-policy',
'https://kgsboutique.com/policies/privacy-policy',
'https://kickbazr.myshopify.com/policies/privacy-policy',
'https://kidventuregear.myshopify.com/policies/privacy-policy',
'https://kinderschuhe-bambini.de/policies/privacy-policy',
'https://kitchenallproduct.myshopify.com/policies/privacy-policy',
'https://kitchenmagictools.com/policies/privacy-policy',
'https://kmluxe.shop/policies/privacy-policy',
'https://koolahofficial.com/policies/privacy-policy',
'https://kronetic.shop/policies/privacy-policy',
'https://ks-shop-9567.myshopify.com/policies/privacy-policy',
'https://kyskingdompublishing.com/policies/privacy-policy',
'https://lacquio.com/policies/privacy-policy',
'https://lafanf.com/policies/privacy-policy',
'https://lamarca-3186.myshopify.com/policies/privacy-policy',
'https://lanelondon.myshopify.com/policies/privacy-policy',
'https://laven-7733.myshopify.com/policies/privacy-policy',
'https://lavendre.fr/policies/privacy-policy',
'https://leggitherm.com/policies/privacy-policy',
'https://lenawagner-modehaus.com/policies/privacy-policy',
'https://lenora-boutique.cz/policies/privacy-policy',
'https://lenora-luxe.myshopify.com/policies/privacy-policy',
'https://lenorea.com/policies/privacy-policy',
'https://liktogoogle.myshopify.com/policies/privacy-policy',
'https://lintify-4.myshopify.com/policies/privacy-policy',
'https://liora-beauty.de/policies/privacy-policy',
'https://lipozemarg.shop/policies/privacy-policy',
'https://littlenestessential.myshopify.com/policies/privacy-policy',
'https://littlesmaison.com/policies/privacy-policy',
'https://littletomo.com/policies/privacy-policy',
'https://liveoutdor.shop/policies/privacy-policy',
'https://livicreativeshop.com/policies/privacy-policy',
'https://livingbalance26.myshopify.com/policies/privacy-policy',
'https://livirelief.com/policies/privacy-policy',
'https://locktitan.store/policies/privacy-policy',
'https://lococlock.shop/policies/privacy-policy',
'https://lojaduccco.shop/policies/privacy-policy',
'https://lojamidas.shop/policies/privacy-policy',
'https://lojamoradaoficial.com/policies/privacy-policy',
'https://lojaoficial1.buscabuscae.shop/policies/privacy-policy',
'https://lomena.fr/policies/privacy-policy',
'https://lomixstore.com/policies/privacy-policy',
'https://losandesmarket.com/policies/privacy-policy',
'https://lovetay1395.myshopify.com/policies/privacy-policy',
'https://low-ball-2.myshopify.com/policies/privacy-policy',
'https://lumenza.shop/policies/privacy-policy',
'https://luminium.store/policies/privacy-policy',
'https://lumixin.fr/policies/privacy-policy',
'https://lumoda.com.co/policies/privacy-policy',
'https://lumolux-2.myshopify.com/policies/privacy-policy',
'https://lumorel.com/policies/privacy-policy',
'https://luna-roma.it/policies/privacy-policy',
'https://lunarescues.online/policies/privacy-policy',
'https://luneaco.in/policies/privacy-policy',
'https://lunvero-pl.myshopify.com/policies/privacy-policy',
'https://luxehairshope.com/policies/privacy-policy',
'https://luxeroadx.com/policies/privacy-policy',
'https://luxify.in/policies/privacy-policy',
'https://luxvalio.com/policies/privacy-policy',
'https://luxybee-2.myshopify.com/policies/privacy-policy',
'https://m2lina.myshopify.com/policies/privacy-policy',
'https://ma-boutique-777994.myshopify.com/policies/privacy-policy',
'https://ma-joli-beauty.myshopify.com/policies/privacy-policy',
'https://machronoband.store/policies/privacy-policy',
'https://madebyregina.com/policies/privacy-policy',
'https://magicscents.online/policies/privacy-policy',
'https://magnesium-body-butter.myshopify.com/policies/privacy-policy',
'https://maktiv.store/policies/privacy-policy',
'https://mamabread.com/policies/privacy-policy',
'https://maminouche.com/policies/privacy-policy',
'https://mammabjorn.se/policies/privacy-policy',
'https://mapaco.shop/policies/privacy-policy',
'https://marchewrld.com/policies/privacy-policy',
'https://mascota.co.in/policies/privacy-policy',
'https://matjarily.store/policies/privacy-policy',
'https://max-trends.com/policies/privacy-policy',
'https://maxp0wer.myshopify.com/policies/privacy-policy',
'https://mayari-eye-wears.myshopify.com/policies/privacy-policy',
'https://mechnaxx.myshopify.com/policies/privacy-policy',
'https://medicubeindia.shop/policies/privacy-policy',
'https://meeshoos.myshopify.com/policies/privacy-policy',
'https://megaafri.com/policies/privacy-policy',
'https://megakarts-in.myshopify.com/policies/privacy-policy',
'https://meialuastore.com/policies/privacy-policy',
'https://menbox.store/policies/privacy-policy',
'https://menscapes.net/policies/privacy-policy',
'https://mercadolivre-com-br-projetor.myshopify.com/policies/privacy-policy',
'https://mervelstore.com/policies/privacy-policy',
'https://methiqabymerzal.shop/policies/privacy-policy',
'https://michaelturneroutlet.com/policies/privacy-policy',
'https://mihuertadesdecero.com/policies/privacy-policy',
'https://milknestco.myshopify.com/policies/privacy-policy',
'https://milliandmollis.com/policies/privacy-policy',
'https://mini-boleteras-de-mx.myshopify.com/policies/privacy-policy',
'https://minicrew-fr.com/policies/privacy-policy',
'https://minimarketse.com/policies/privacy-policy',
'https://miraclesscents.com/policies/privacy-policy',
'https://mmq3kr-fc.myshopify.com/policies/privacy-policy',
'https://modaflaree.myshopify.com/policies/privacy-policy',
'https://monocarry.com/policies/privacy-policy',
'https://morane-texas.com/policies/privacy-policy',
'https://moreofneon.com/policies/privacy-policy',
'https://moringa-8473.myshopify.com/policies/privacy-policy',
'https://morumousa.com/policies/privacy-policy',
'https://motiwalawatches.com/policies/privacy-policy',
'https://mu3tyy-y4.myshopify.com/policies/privacy-policy',
'https://myalmora.store/policies/privacy-policy',
'https://myavola.store/policies/privacy-policy',
'https://mycqin-vi.myshopify.com/policies/privacy-policy',
'https://myfzbrand3565634.myshopify.com/policies/privacy-policy',
'https://mykitchenitemstore.myshopify.com/policies/privacy-policy',
'https://mykitchenstoree.myshopify.com/policies/privacy-policy',
'https://myshops.live/policies/privacy-policy',
'https://mysimplycurated.com/policies/privacy-policy',
'https://mystlegacy.com/policies/privacy-policy',
'https://mystore-123456789789457354.myshopify.com/policies/privacy-policy',
'https://n69g7i-0x.myshopify.com/policies/privacy-policy',
'https://nanohertztechnologies.com/policies/privacy-policy',
'https://nationalhelthauthorise.myshopify.com/policies/privacy-policy',
'https://nativalabsco.myshopify.com/policies/privacy-policy',
'https://necessaryforyou.com/policies/privacy-policy',
'https://neevura.com/policies/privacy-policy',
'https://nelsoon-2.myshopify.com/policies/privacy-policy',
'https://nelvo.eu/policies/privacy-policy',
'https://neocelle.com/policies/privacy-policy',
'https://nestella.one/policies/privacy-policy',
'https://neurolyn.store/policies/privacy-policy',
'https://nexan.shop/policies/privacy-policy',
'https://nexiaworks.com/policies/privacy-policy',
'https://nexonstore.online/policies/privacy-policy',
'https://nisafiro.online/policies/privacy-policy',
'https://nizzyclx.myshopify.com/policies/privacy-policy',
'https://nodoksanalti.com/policies/privacy-policy',
'https://noobe-ecom-africa.myshopify.com/policies/privacy-policy',
'https://nook-book.store/policies/privacy-policy',
'https://nordbeamsverige.se/policies/privacy-policy',
'https://nordicmotive.se/policies/privacy-policy',
'https://nordiskmassage.de/policies/privacy-policy',
'https://nordixstore.se/policies/privacy-policy',
'https://novacart-c.myshopify.com/policies/privacy-policy',
'https://novaelitegadjet-2.myshopify.com/policies/privacy-policy',
'https://novaheat.online/policies/privacy-policy',
'https://nuborelax.com/policies/privacy-policy',
'https://nukhbabuy.store/policies/privacy-policy',
'https://nuraglow.online/policies/privacy-policy',
'https://nuvarape.myshopify.com/policies/privacy-policy',
'https://nuvella.pro/policies/privacy-policy',
'https://nuvionbyscience.com/policies/privacy-policy',
'https://nux-cosmetic.com/policies/privacy-policy',
'https://nxtte.com/policies/privacy-policy',
'https://oasis-280521.myshopify.com/policies/privacy-policy',
'https://officialelyra.com/policies/privacy-policy',
'https://officialluminexis.com/policies/privacy-policy',
'https://officiallunora.com/policies/privacy-policy',
'https://officialzelliwellness.com/policies/privacy-policy',
'https://ohhsugar.store/policies/privacy-policy',
'https://oldschoolpretoriaretail.com/policies/privacy-policy',
'https://omuzdestekpro.store/policies/privacy-policy',
'https://onaedept.com/policies/privacy-policy',
'https://one-piecefanshop.myshopify.com/policies/privacy-policy',
'https://opexclothin.myshopify.com/policies/privacy-policy',
'https://orbeo.store/policies/privacy-policy',
'https://organic-shop-123128.myshopify.com/policies/privacy-policy',
'https://orthopedicslibrary.online/policies/privacy-policy',
'https://ortovida.online/policies/privacy-policy',
'https://otrix-store.com/policies/privacy-policy',
'https://ouin-ouin-ouin.com/policies/privacy-policy',
'https://outdorcamp.shop/policies/privacy-policy',
'https://outlet-grenoble.com/policies/privacy-policy',
'https://oveora.com/policies/privacy-policy',
'https://p0rg0w-13.myshopify.com/policies/privacy-policy',
'https://pacificpk.store/policies/privacy-policy',
'https://packify-reel.myshopify.com/policies/privacy-policy',
'https://paradiseelixirs.store/policies/privacy-policy',
'https://pardonruined.com/policies/privacy-policy',
'https://patitasviralesargentina.myshopify.com/policies/privacy-policy',
'https://pawperimeter.com/policies/privacy-policy',
'https://pawprint-lab.myshopify.com/policies/privacy-policy',
'https://pawtraitstudio.online/policies/privacy-policy',
'https://pdfzone.myshopify.com/policies/privacy-policy',

]
RemainingURLs = []

def find_emails_in_text(scoutURL):
    # try:        
    secondPage = requests.get(scoutURL, timeout=2)

    # htmlcontent = secondPage.text

    secSoup = BeautifulSoup(secondPage.text, "html.parser")

    # secondResults = secSoup.find(id="MainContent")

    secondPython_jobs = secSoup.get_text()
    # print(type(secondPython_jobs))
    # print(secondPython_jobs)

    email_pattern = r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"
    emails = [] 
    # for paragraph in secondPython_jobs:
    found_emails = re.findall(email_pattern, secondPython_jobs)
    emails.extend(found_emails)

    print(emails)
    return emails
    # except:
    #     print(f"Error fetching {scoutURL}")
    #     RemainingURLs.append(scoutURL)
    #     return []

# find_emails_in_text(scoutURL)



# for i in scouting_URLS:
#     find_emails_in_text(i)
    
# print(RemainingURLs)

def getemails(data):
    emails_found = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        futures = [executor.submit(find_emails_in_text, url) for url in data] 
        for future in concurrent.futures.as_completed(futures):
            try:
                emails = future.result()
                emails_found.extend(emails)
            except Exception as e:
                # print(f"Error occurred: {e}")
                RemainingURLs.append(scoutURL)
                
    print("Finished processing all URLs.")  
    print("Remaining URLs:")        
    print(RemainingURLs)
    print("Emails found:")
    unique_emails = set(emails_found)
    emails_found = list(unique_emails)
    print(emails_found)
    return emails_found